# Problem 44
#
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
#
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

def pent(n)
    return (n*(3*n-1))/2
end

def inv_pent(n)
    ind = (1.0 + Math.sqrt(1.0 + 24.0*n)) / 6.0
    return (ind+0.5).floor
end

max_n = 100000000

for k in 1..max_n
    diff = pent(k) # The difference must be a pentagonal number
    print "k=#{k}, diff=#{diff}\n"
    for i in 1..k*k
        pi = pent(i) # This is the smaller of the two
        pj = pi + diff

        j = inv_pent(pj)

        if i == j
            break
        end

        if pent(j) != pj
            next
        end

        sum = pi+pj
        s = inv_pent(sum)
        if pent(s) != sum
            next
        end

        print "k=#{k}, diff=#{diff}, pi=#{pi}, pj=#{pj}, i=#{i}, j=#{j}\n"
        exit

    end
end

